### ISSUE TITLE
nameof(crate::test)

### ISSUE THREAD

**Issue by Silentdoer** [SilentByte/nameof#4]
return crate::test &str

**Comment by SilentByte** [comment]
你好。不好意思，我不懂你在说什么。你能解释一下吗？

**Comment by Silentdoer** [comment]
原来是国人啊，我英语不好所以不敢多写。。我的意思是能否加个类似path_of_fn!(crate::aa::test)然后返回crate::aa::test这个字符串，rust里validator有这个的话会比较方便，你觉得可以的话我这边可以提个pr
