### ISSUE TITLE
Now closures must be used: https://github.com/rust-lang/rust/pull/74869

### ISSUE THREAD

**Issue by A1-Triard** [SilentByte/nameof#5]
In new nightly `name_of!` macro generates "unused closure that must be used" warning.

I think, `let _ = ` should be added to suppress the warning.

**Comment by SilentByte** [comment]
Thanks for letting me know! I published a new version, the warnings should be fixed now.

**Comment by A1-Triard** [comment]
Yes, it is fixed, thank you.

**Comment by Jake-S6** [comment]
I still get this warning on 1.2.1

**Comment by A1-Triard** [comment]
> I still get this warning on 1.2.1

It looks strange. Are you sure the 1.2.1 version is in Cargo.lock? Have you tried to execute `cargo update`?
